resources:
  - name: test
    type: git
    source:
      uri: https://github.com/riteshbabu/concourse-demo.git
      branch: master

jobs:
- name: test
  plan:
  - get: test
    trigger: true
 # - task: install
 #   file: sources/pipeline/install.yml
  - task: test
    file: test/pipeline/test.yml
